apiVersion: devtool/v1
kind: RenderDocument
metadata:
  name: SEC-10
spec:
  notWanted:
    - heading: 10. Arquitetura Operacional
      children:
      - heading: Definições e Decisões
      - heading: Entregáveis
      - heading: Definições Utilizadas
      - heading: Decisões Referenciadas
      - heading: Itens Pendentes
      - heading: Perguntas para o Utilizador

