apiVersion: devtool/v1
kind: RenderDocument
metadata:
  name: SEC-07
spec:
  notWanted:
    - heading: 7. Autenticação & Autorização
      children:
      - heading: Definições e Decisões
      - heading: Entregáveis
      - heading: Definições Utilizadas
      - heading: Decisões Referenciadas
      - heading: Itens Pendentes
      - heading: Perguntas para o Utilizador



